// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application";

import LuiCommandController from "./lui/command_controller";
import LuiCommandItemController from "./lui/command_item_controller";
import LuiCommandPopoverController from "./lui/command_popover_controller";


application.register("lui--command", LuiCommandController);
application.register("lui--command-item", LuiCommandItemController);
application.register("lui--command-popover", LuiCommandPopoverController);